### ISSUE TITLE
-alg:her gives error AttributeError: 'Box' object has no attribute 'spaces'

### ISSUE THREAD

**Issue by stefanwanckel** [PierreExeter/rl_reach#1]
Running the function run_experiments.py with the flag alg:her gives me the following error message:

> python run_experiments.py --exp-id 96 --algo her --env widowx_reacher-v2 --n-timesteps 10000 --n-seeds 2
> Exp #96: Training env widowx_reacher-v2 with algo her and seed 0...
> Traceback (most recent call last):
>   File "train.py", line 272, in <module>
>     model = exp_manager.setup_experiment()
>   File "/home/stefan/Documents/Masterarbeit/rl_reach/code/utils/exp_manager.py", line 159, in setup_experiment
>     env = self.create_envs(self.n_envs, no_log=False)
>   File "/home/stefan/Documents/Masterarbeit/rl_reach/code/utils/exp_manager.py", line 574, in create_envs
>     env = ObsDictWrapper(env)
>   File "/home/stefan/anaconda3/envs/rl_reach/lib/python3.7/site-packages/stable_baselines3/common/vec_env/obs_dict_wrapper.py", line 21, in __init__
>     self.spaces = list(venv.observation_space.spaces.values())
> AttributeError: 'Box' object has no attribute 'spaces'
> Exp #96: Training env widowx_reacher-v2 with algo her and seed 1...
> Traceback (most recent call last):
>   File "train.py", line 272, in <module>
>     model = exp_manager.setup_experiment()
>   File "/home/stefan/Documents/Masterarbeit/rl_reach/code/utils/exp_manager.py", line 159, in setup_experiment
>     env = self.create_envs(self.n_envs, no_log=False)
>   File "/home/stefan/Documents/Masterarbeit/rl_reach/code/utils/exp_manager.py", line 574, in create_envs
>     env = ObsDictWrapper(env)
>   File "/home/stefan/anaconda3/envs/rl_reach/lib/python3.7/site-packages/stable_baselines3/common/vec_env/obs_dict_wrapper.py", line 21, in __init__
>     self.spaces = list(venv.observation_space.spaces.values())
> AttributeError: 'Box' object has no attribute 'spaces'
> 

I suspect it must have something to do with the observation space being a dictionary. 
Maybe you can give me a hint on how to resolve this issue.
Thanks in advance

**Comment by stefanwanckel** [comment]
widowx_reacher-v2 does not inherit goal_env which is a requirement for hindsight experience replay.
However, the observation is stored in a dictionary if the parameter 'goal_oriented' is set to True in the __init__.py file.
But none of the 32 environments registered in the __init__.py file have set goal_oriented=True. 
So maybe I am misunderstanding something.

**Comment by PierreExeter** [comment]
Hi Stefan,

In order to use HER, you need a goal_oriented environment and you're correct, this will make your observation become a dictionary.

There's a few things to check:
-  set `goal_oriented` to True in [__init__.py](https://github.com/PierreExeter/rl_reach/blob/master/code/gym_envs/widowx_env/__init__.py)
-  make sure the [hyperparameters](https://github.com/PierreExeter/rl_reach/blob/master/code/hyperparams/her.yml) exist for the environment you're looking at
- I just realised that the [compute_reward](https://github.com/PierreExeter/rl_reach/blob/8a0aaa126c6483a35ea6de5361523ccaf22a289a/code/gym_envs/widowx_env/envs/widowx_env.py#L789) function is missing an argument. It should read:
`def compute_reward(self, achieved_goal, goal, info):`
instead of
`compute_reward(self, achieved_goal, goal):`
I will fix this in a future commit.

I can't reproduce your error so it may be due to using an old version.
How did you install rl_reach? Which commit ID?

**Comment by stefanwanckel** [comment]
After following all steps you proposed, it worked.

The environment needed objectDictWrapper in the hyperparameter yml.

thank you so much!

**Comment by PierreExeter** [comment]
I'm glad you figured it out :)
